dataset_path: '../../data/TVSum/processed/eccv16_dataset_tvsum_google_pool5.h5'
eval_method: 'max' #'avg'
video_scores: 'video_scores.txt'
fscores: 'f_scores.txt'
path: '../exp1/tvsum/results'
splits: ['split0','split1','split2','split3','split4']